alertlogic/nepal-client-libs

packages/deployments-client/package.json

To purge some bad typings in 2.0.3

@al/deployments 2.0.4

---

packages/assets-query-client/package.json
packages/assets-query-client/src/al-assets-query-client.ts
packages/assets-query-client/src/index.ts
packages/assets-query-client/src/types/index.ts
packages/assets-query-client/test/assets-query-client.spec.ts
packages/policies-client/package.json
packages/policies-client/src/al-policies-client.ts
packages/policies-client/src/index.ts
packages/policies-client/src/types/index.ts

Refactoring of assets-query and policies libs and bumps of both to 2.0.4

US000000 - Lib Refactors

---

packages/assets-query-client/package.json
packages/assets-query-client/src/al-assets-query-client.ts

This allows multiple filter values to be supplied as supported by the backend

US00000 - 2.0.5 - update some param types

---

packages/assets-query-client/package.json
packages/assets-query-client/src/types/asset-type-dictionary.class.ts
packages/assets-query-client/src/types/index.ts

Import of `AssetTypeDictionary` from `@o3/core`

US000000 - 2.0.6 - bring in AssetTypeDictionary from @o3/core

---

packages/vr-test-helper/package.json
packages/vr-test-helper/src/e2e-shared/login.spec.js

Bringing in shared e2e login spec from @o3/core

US000000 - add shared e2e login spec

---

packages/tacoma-client/package.json
packages/tacoma-client/src/types/index.ts

https://console.account.product.dev.alertlogic.com/users/api/tacoma/index.html#api-Views-GetView

US000: tacomaView adding false to schedule_frequency

---

packages/assets-query-client/src/types/index.ts

[Jira](https://alertlogic.atlassian.net/browse/ENG-3551)

ENG-3551 - Coverage & Health Dashboard - Add Collectors health status widget

---

packages/assets-query-client/package.json
packages/assets-query-client/src/types/health-assets.ts
packages/assets-query-client/src/types/index.ts

Once changes are live from pr to AL asset_query this pr can be merged.

ENG-3612 - Health Console - Collectors - Interface update for collector asset

---

packages/assets-query-client/package.json

[Jira](https://alertlogic.atlassian.net/browse/ENG-3551)

ENG-3551 - Coverage & Health Dashboard - Add Collectors health status widget (incrementing version)

---

packages/sources-client/src/types/types.ts

Adding missing properties to the EnvironmentSource interface.

ENG-3123 - Nepalization of o3-remediations

---

packages/nepal-integrations-client/LICENSE
packages/nepal-integrations-client/README.md
packages/nepal-integrations-client/karma.conf.js
packages/nepal-integrations-client/package.json
packages/nepal-integrations-client/src/al-integrations-client.ts
packages/nepal-integrations-client/src/index.ts
packages/nepal-integrations-client/src/types/index.ts
packages/nepal-integrations-client/src/types/integrationsTypes.ts
packages/nepal-integrations-client/test/al-integrations-client.spec.ts
packages/nepal-integrations-client/tsconfig.json
packages/nepal-integrations-client/tsconfig.spec.json

adding the base
adding integrations and integrations/name

ENG-5751: adding the integrations client part 0

---

packages/fim-client/package.json
packages/fim-client/src/al-fim-client.ts
packages/fim-client/src/types/index.ts
packages/fim-client/test/al-fim-client.spec.ts

FIM API: https://console.account.product.dev.alertlogic.com/users/api/fim_config/index.html#api-Reports-GetSummary
[Jira](https://alertlogic.atlassian.net/browse/ENG-3048)

ENG-3048 - Adding getConfigurationsSummary method [GET]

---

packages/assets-query-client/package.json
packages/assets-query-client/src/types/health-assets.ts

- state field added to HealthAssetVPC type

ENG-6368: Fixing missing fields in health views

---

packages/nepal-integrations-client/package.json
packages/nepal-integrations-client/src/types/integrationsTypes.ts

[Jira](https://alertlogic.atlassian.net/browse/ENG-6827)

ENG-6350 - Add icon property to AlIntegrationType

---

packages/suggestions/package.json
packages/suggestions/src/suggestions-client-v2.ts
packages/suggestions/src/types/al-suggestions.types-v2.ts

ENG-7118: Adding Templates and Saved Searches CRUD

---

packages/integrations/package.json
packages/integrations/src/types/integrationsTypes.ts

US000:refactor integrations

---

packages/cargo/package.json
packages/cargo/src/types/types-v2.ts

[JIRA ENG-7911](https://alertlogic.atlassian.net/browse/ENG-7911)

ENG-7911 - Adding new fields to the cargo artifact data

---

packages/suggestions/package.json
packages/suggestions/src/types/al-suggestions.types-v2.ts

[JIRA ENG-13067](https://alertlogic.atlassian.net/browse/ENG-13067)

ENG-13067 - Adding template field to the saved searches

---

packages/assets-query/package.json
packages/assets-query/src/al-assets-query-client.ts
packages/assets-query/src/types/assets/asset-groups.ts
packages/assets-query/src/types/assets/index.ts

Service to create, delete and update an asset group

ENG-14868: [UI] - Asset Group - Client for UI

---

package.json
packages/vr-test-helper/package.json
packages/vr-test-helper/src/element-helpers.ts
packages/vr-test-helper/src/visual-regression-test-helpers.ts

[Jira](https://alertlogic.atlassian.net/browse/ENG-15674)

ENG-15674 - Migrate our Visual Regression test to start using puppeteer instead of protractor

---

packages/responder/package.json
packages/responder/src/al-responder-client.ts
packages/responder/src/types/playbookTypes.ts

https://alertlogic.atlassian.net/browse/SP-20

SP-20: adding actions to responder client

---

packages/assets-query/package.json
packages/assets-query/src/types/assets/asset-type-dictionary.class.ts

ENG-0000 : Icon change for s3-bucket 

---

packages/assets-query/package.json
packages/assets-query/src/al-assets-query-client.ts
packages/assets-query/src/types/index.ts

Additional params and response properties added to bring in latest changes for the following endpoints:
- https://console.account.product.dev.alertlogic.com/users/api/assets_query/index.html#api-Remediations-QueryRemediationItems
- https://console.account.product.dev.alertlogic.com/users/api/assets_query/index.html#api-Remediations-DisposeRemediations
- https://console.account.product.dev.alertlogic.com/users/api/assets_query/index.html#api-Remediations-ConcludeRemediations
- https://console.account.product.dev.alertlogic.com/users/api/assets_query/index.html#api-Remediations-UndisposeRemediations

ENG-0000: update dispose\conclude operations with latest backend changes

---

packages/vr-test-helper/package.json
packages/vr-test-helper/src/element-helpers.ts

ENG-16760 - Generate visual regression report in a HTML that can be imported in the PR

---

packages/responder/package.json
packages/responder/src/al-responder-client.ts
packages/responder/src/types/playbookTypes.ts

https://alertlogic.atlassian.net/browse/SP-46

SP-46: responder add get schemas

---

packages/suggestions/package.json
packages/suggestions/src/suggestions-client-v2.ts
packages/suggestions/src/types/al-suggestions.types-v2.ts

Adds a simple datatype and two methods for retrieving enumerated fields
and enumerated values.

ENG-5724 - Suggestions/v2 Integration in SMS

---

packages/assets-query/package.json
packages/assets-query/src/types/index.ts

Just adding some missing interface fields...

ENG-17013: update typings for assets-query client

---

packages/dashboards/package.json
packages/dashboards/src/types/index.ts

[Jira](https://alertlogic.atlassian.net/browse/ENG-17410)

ENG-17410 - Adding time indicator

---

packages/assets-query/package.json
packages/assets-query/src/al-assets-query-client.ts
packages/assets-query/src/types/assets/asset-groups.ts

https://alertlogic.atlassian.net/browse/ENG-18189

add listAssetGroups for assets-query

---

packages/assets-query/package.json
packages/assets-query/src/al-assets-query-client.ts
packages/assets-query/src/types/index.ts
packages/assets-query/test/assets-query-client.spec.ts

https://alertlogic.atlassian.net/browse/ENG-17155

ENG-17155: update tags summary implementation

---

packages/suggestions/package.json
packages/suggestions/src/suggestions-client-v2.ts
packages/suggestions/src/types/al-suggestions.types-v2.ts

Updates the suggestions/v2 client to work with the latest changes to the
API.

ENG-5724 - Suggested Fields in SMS

---

packages/distribution-client/LICENSE
packages/distribution-client/README.md
packages/distribution-client/karma.conf.js
packages/distribution-client/package.json
packages/distribution-client/src/al-distributor-client.ts
packages/distribution-client/src/index.ts
packages/distribution-client/test/al-distributor-client.spec.ts
packages/distribution-client/tsconfig.json
packages/distribution-client/tsconfig.spec.json

[Jira](https://alertlogic.atlassian.net/browse/ENG-18472)

ENG-18472 - Adding distributor client

---

packages/assets-query/package.json
packages/assets-query/src/al-assets-query-client.ts
packages/assets-query/src/types/assets/asset-groups.ts

Just adding some new params to coincide with recent backend changes to this endpoint.

ENG-17251: update params for asset group topology

---

package.json
packages/assets-query/package.json
packages/assets-query/src/al-assets-query-client.ts
packages/assets-query/src/types/assets/asset-types.ts

Adding functionality to integrate with fetching asset types as per recent endpoint added here https://console.account.product.dev.alertlogic.com/users/api/assets_query/index.html#api-AssetTypes-AssetTypesSchema

ENG-17251: add functionality to retrieve asset type schema details

---

packages/kalm/package.json
packages/kalm/src/al-kalm-client.ts
packages/kalm/src/index.ts
packages/kalm/test/karma-client.spec.ts

- Improvements to @al/kalm to better bundle output, make the typings actually discoverable in TS based projects!

ENG-19312: modernize @al/kalm in line with other libs, improve build output, etc

---

packages/suggestions/package.json
packages/suggestions/src/types/al-suggestions.types-v2.ts

Added `type` property to suggestions/v2 enumerated field record.

ENG-0000 - enumeration type property

---

packages/iris/package.json
packages/iris/src/al-iris-client.ts

[Jira](https://alertlogic.atlassian.net/browse/ENG-19606)

ENG-19606 - Addding retinaSearch endpoint to iris client

---

packages/responder/package.json
packages/responder/src/types/playbookTypes.ts

ENG-19274: AlResponderPlaybookParameter: add properties

---

packages/iris/package.json
packages/iris/src/al-iris-client.ts
packages/iris/src/types/index.ts

[ENG-19515](https://alertlogic.atlassian.net/browse/ENG-19515)

ENG-19515 - Adding IRIS method to retrieve the columns and filters

---

packages/assets-query/package.json
packages/assets-query/src/types/assets/asset-groups.ts
packages/assets-query/src/types/index.ts

https://alertlogic.atlassian.net/browse/ENG-17157
- Just some typings updates

ENG-17157: @al/assets-query - updating types

---

packages/iris/package.json
packages/iris/src/al-iris-client.ts
packages/iris/src/types/additional-evidence-types.ts
packages/iris/src/types/index.ts

US: [ENG-20639](https://alertlogic.atlassian.net/browse/ENG-20639?atlOrigin=eyJpIjoiY2JiMWE3NjM5YzZmNGU3Y2I3ZTRhZGJiMzYzZjhmNzciLCJwIjoiaiJ9)

ENG-20639 - adding additional evidence endpoint to iris

---

packages/iris/package.json
packages/iris/src/types/additional-evidence-types.ts

US: [ENG-20639](https://alertlogic.atlassian.net/browse/ENG-20639?atlOrigin=eyJpIjoiY2JiMWE3NjM5YzZmNGU3Y2I3ZTRhZGJiMzYzZjhmNzciLCJwIjoiaiJ9)

ENG-20639 - updating AdditionalEvidenceResponse type

---

packages/iris/src/al-iris-client.ts

[ENG-19830](https://alertlogic.atlassian.net/browse/ENG-19830)

ENG-19830 - Adding new endpoint for csv download to iris client

---

packages/iris/package.json
packages/iris/src/al-iris-client.ts

[ENG-21682](https://alertlogic.atlassian.net/browse/ENG-21682)

ENG-21682 - Changing csv download file type to zip file.

---

package.json
packages/kalm/package.json
packages/kalm/src/al-kalm-client.ts
packages/kalm/src/schemas/kalm.schematics.ts
packages/kalm/test/karma-client.spec.ts

https://alertlogic.atlassian.net/browse/ENG-19821

ENG-19821 - Adding Kalm JSON schema

---

packages/assets-query/package.json
packages/assets-query/src/types/assets/asset-groups.ts

https://alertlogic.atlassian.net/browse/ENG-22202
- Add further props to types for asset groups

ENG-22202: typings updates for @al/assets-query

---

packages/iris/package.json
packages/iris/src/types/al-observation.ts

US: [ENG-22570](https://alertlogic.atlassian.net/browse/ENG-22570?atlOrigin=eyJpIjoiYmE2ZmY2YzA0OTQzNDZjZGI0Nzg3OTlkN2UyMzY5Y2QiLCJwIjoiaiJ9)

ENG-22570 - adding properties to parents in AlObservation type

---

package.json
packages/iris/package.json
packages/iris/src/types/incident.class.ts
packages/iris/src/types/index.ts

[Jira](https://alertlogic.atlassian.net/browse/ENG-22953)

ENG-22953 - Moving incident class to iris client

---

packages/responder/package.json
packages/responder/src/al-responder-client.ts
packages/responder/src/types/playbookTypes.ts

https://alertlogic.atlassian.net/browse/ENG-23376

ENG-23376: responder adding sample payload part 1

---

packages/iris/package.json
packages/iris/src/al-iris-client.ts

[ENG-23314](https://alertlogic.atlassian.net/browse/ENG-23314)

ENG-23314 - Adding markdown render endpoint to iris client

---

packages/iris/package.json
packages/iris/src/types/incident.class.ts

US: [ENG-23448](https://alertlogic.atlassian.net/browse/ENG-23448?atlOrigin=eyJpIjoiNzAxZTM4ZTIxMGI0NGNmZTkyNDA1YzY3ZmVhOTg2NmMiLCJwIjoiaiJ9)

ENG-23448 - adding incident property to Incident type

---

packages/asi/LICENSE
packages/asi/README.md
packages/asi/karma.conf.js
packages/asi/package.json
packages/asi/src/al-asi-client.ts
packages/asi/src/index.ts
packages/asi/src/types/index.ts
packages/asi/test/al-asi-client.spec.ts
packages/asi/tsconfig.json
packages/asi/tsconfig.spec.json

[Jira](https://alertlogic.atlassian.net/browse/ENG-25161)

ENG-25161  - Create api client for ASI service

---

packages/aecontent/LICENSE
packages/aecontent/README.md
packages/aecontent/karma.conf.js
packages/aecontent/package.json
packages/aecontent/src/aecontent-client.ts
packages/aecontent/src/index.ts
packages/aecontent/test/aecontent-client.spec.ts
packages/aecontent/tsconfig.json
packages/aecontent/tsconfig.spec.json
packages/aefr/LICENSE
packages/aefr/README.md
packages/aefr/karma.conf.js
packages/aefr/package.json
packages/aefr/src/aefr-client.ts
packages/aefr/src/index.ts
packages/aefr/test/aefr-client.spec.ts
packages/aefr/tsconfig.json
packages/aefr/tsconfig.spec.json
packages/aerta/package.json
packages/aerta/src/aerta-client.ts
packages/aerta/test/aerta-client.spec.ts

Waiting for backend to make changes before verifying and merging.

[ENG-27290] Add support for getting aecontent and aefr by path (similar to RTA) for IRIS UI

---

packages/applications/package.json
packages/applications/src/types/index.ts

[Jira](https://alertlogic.atlassian.net/browse/ENG-27622)

ENG-27622 - Implement subcategories in application registry

---

packages/iris/package.json
packages/iris/src/al-iris-client.ts

US: [ENG-27653](https://alertlogic.atlassian.net/browse/ENG-27695)

ENG-27653 - adding getCsvIncidentEvidence endpoint to iris service

---

packages/kalm/package.json
packages/kalm/src/al-kalm-client.ts

[ENG-28821](https://alertlogic.atlassian.net/browse/ENG-28821)

ENG-28821 - Adding query stream endpoint to the kalm service

---

packages/loki/package.json
packages/loki/src/loki-client.ts
packages/loki/src/loki-client.type.ts

[API Documentation](https://console.account.product.dev.alertlogic.com/users/api/loki/index.html)

ENG-29433: improve typedef for loki client

---

packages/responder/package.json
packages/responder/src/types/playbookTypes.ts

'mitre_classifications' and 'detection_sources'

ENG-29259: Add incident trigger filters

---

package.json
packages/vr-test-helper/package.json

Updated @al/vr-test-helper to use protractor 7; bumped to new major
version.

ENG-0000 - Angular 11 Compatible VR Test Helpers

---

ps_spec.yml

ENG-0000 - Publish experimental version

---

packages/vr-test-helper/package.json

ENG-0000 - Bumped Dep

---

packages/kalm/package.json
packages/kalm/src/al-kalm-client.ts

[ENG-30407](https://alertlogic.atlassian.net/browse/ENG-30407)
Info: Change download endpoint for TIC.
Create a new function for to call a new repository
Before
https://api.cloudinsight.alertlogic.com/kalm/v1/<account_id>/query/tic_analytics/archive/?params..
After:
https://api.cloudinsight.alertlogic.com/kalm/v1/<account_id>/query/tic_analytics/?export_format=csv

ENG-30407 - Change download endpoint for TIC

---

packages/cargo/src/types/types-v1.ts

[Jira](https://alertlogic.atlassian.net/browse/VTT-3528)

VTT-3528 - Saved Searches: Unable to save updated checkbox value for 'Include Zero Result Searches'

---

packages/connectors/package.json
packages/connectors/src/al-connectors-client.ts

[Jira](https://alertlogic.atlassian.net/browse/ENG-31516)

ENG-31516 - Enable Connectors with Account Scope - Palo Alto

---

packages/responder/package.json
packages/responder/src/al-responder-client.ts
packages/responder/src/types/playbookTypes.ts
packages/responder/test/al-responder-client.spec.ts

[Jira](https://alertlogic.atlassian.net/browse/ENG-32505)

ENG-32505 - Create CRUD functions and types for Responses

---

packages/responder/package.json
packages/responder/src/types/playbookTypes.ts

US - https://alertlogic.atlassian.net/browse/ENG-31135

ENG-31135 - Adding Title Param

---

packages/deployments/package.json
packages/deployments/src/types/index.ts

Change based on:
[deployments api](https://algithub.pd.alertlogic.net/raw/defender/deployments/master/doc/openapi/deployments.v1.yaml)

ENG-32814: Adding features property into Deployment interface

---

packages/iris/src/types/incident.class.ts

US: [ENG-32834](https://alertlogic.atlassian.net/browse/ENG-32834)

ENG-32834 - adding collectorName property to Incident class

---

packages/responder/package.json
packages/responder/src/al-responder-client.ts
packages/responder/src/types/playbookTypes.ts
packages/responder/test/al-responder-client.spec.ts

[Jira](https://alertlogic.atlassian.net/browse/ENG-31769)

ENG-31769 - Add get MR config definitions to responder client

---

packages/iris/package.json
packages/iris/src/types/incident.class.ts

US: [ENG-34025](https://alertlogic.atlassian.net/browse/ENG-34025)

ENG-34025 - adding collector type property to incident class

---

packages/responder/package.json
packages/responder/src/types/playbookTypes.ts

[ENG-34118](https://alertlogic.atlassian.net/browse/ENG-34118)

ENG-34118 - Add schema property for definitions interface

---

packages/convergence-utility/LICENSE
packages/convergence-utility/README.md
packages/convergence-utility/karma.conf.js
packages/convergence-utility/package.json
packages/convergence-utility/src/convergence-utility-client.ts
packages/convergence-utility/src/index.ts
packages/convergence-utility/test/convergence-utility-client.spec.ts
packages/convergence-utility/tsconfig.json
packages/convergence-utility/tsconfig.spec.json

[ENG-29912](https://alertlogic.atlassian.net/browse/ENG-29912)

ENG-29912 - Creating convergence utility client

---

packages/cargo/package.json
packages/cargo/src/types/types-v2.ts

US - https://alertlogic.atlassian.net/browse/ENG-33919

ENG-33919 - Adding Number Type

---

packages/connectors/package.json
packages/connectors/src/al-connectors-client.ts
packages/responder/package.json
packages/responder/src/types/playbookTypes.ts

[ENG-3443](https://alertlogic.atlassian.net/browse/ENG-34443)

ENG-3443 - Add property connection_target_types

---

packages/iris/package.json
packages/iris/src/types/incident.class.ts

US: [ENG-32835](https://alertlogic.atlassian.net/browse/ENG-32835)

ENG-32835 - adding properties attribute to Incident class

---

package.json
tsconfig.json

Upgraded typescript
Added path entry so one client can refer to another

ENG-0000 - typescript 3.9

---

packages/responder/package.json
packages/responder/src/types/playbookTypes.ts

This reverts commit 596be6957870974c3191a1d3ba11fd982a511fea.

"ENG-35674 - Revert: add the allowed values property to definitions (#557) pardon my stupidity Mr. Eche"

---

packages/aetag/package.json
packages/aetag/src/aetag-client.ts

US: [ENG-35445](https://alertlogic.atlassian.net/browse/ENG-35445)

ENG-35445 - updating aetag client

---

packages/assets-query/package.json
packages/assets-query/src/types/index.ts

- Just exposing a recently added param by backend for querying exposures -  a more lightweight detailed response

ENG-0000: add new exposures query param

---

packages/iris/package.json
packages/iris/src/types/source-type.class.ts

[ENG-35505](https://alertlogic.atlassian.net/browse/ENG-35505)

ENG-35505 - Adding new evidence type application/x-alpacket-idsmsgs

---

packages/iris/package.json
packages/iris/src/al-iris-client.ts

US: [ENG-36155](https://alertlogic.atlassian.net/browse/ENG-36155)

ENG-36155 - adding /searches endpoint to iris client

---

packages/serca/LICENSE
packages/serca/README.md
packages/serca/karma.conf.js
packages/serca/package.json
packages/serca/src/al-serca-client.ts
packages/serca/src/index.ts
packages/serca/src/types/index.ts
packages/serca/test/al-cerca-client.spec.ts
packages/serca/tsconfig.json
packages/serca/tsconfig.spec.json

US - https://alertlogic.atlassian.net/browse/ENG-36560

ENG-36560 - Adding Serca Client

---

packages/scan-scheduler/package.json
packages/scan-scheduler/src/types/scanSchedule.ts

[ENG-36507](https://alertlogic.atlassian.net/browse/ENG-36507)

ENG-36507 - Adding new schedule frequency and type

---

packages/iris/package.json
packages/iris/src/al-iris-client.ts

This reverts commit 937c12c9eab296b9731c86a42529797d5e6bb466.

Revert "[VTT-4163] nested evidences call is always US residency (#597)"

---

packages/responder/package.json
packages/responder/src/al-responder-client.ts
packages/responder/src/types/playbookTypes.ts

[ENG-36538](https://alertlogic.atlassian.net/browse/ENG-36538)

ENG-36538 - New endpoint for AR block status management

---

packages/iris/package.json
packages/iris/src/al-iris-client-v3.ts
packages/iris/src/index.ts

[ENG-38953](https://alertlogic.atlassian.net/browse/ENG-38953)

ENG-38366 - Creating Iris client v3

---

packages/exclusions/package.json
packages/exclusions/src/types/index.ts

Adding support for agent_scanning exclusion types

ENG-40123: [UI] Add  Agent Based Exclusions

---

packages/assets-query/package.json
packages/assets-query/src/types/index.ts

Just an addition of a new optional param from backend to reduce size of response payload

ENG-0000: update param types

---

packages/iris/package.json
packages/iris/src/al-iris-client-v3.ts

**US**: [ENG-42014](https://alertlogic.atlassian.net/browse/ENG-42014)

ENG-42014 - adding reelaborate incident endpoint to iris v3 client

---

packages/assets-query/package.json
packages/assets-query/src/types/assets/phoenix-topology-snapshot.class.ts

Bug: _not showing data in the Remediations and Continous Scan dashboards for any customer_

VTT-4643: Fix topology snapshot

---

packages/credentials/package.json
packages/credentials/src/al-credentials-client.ts
packages/credentials/src/types/index.ts

I will need to refactor [this file](https://algithub.pd.alertlogic.net/defender/o3-configuration/blob/6721374e969040514035e7e8b06dfe1759dd91b4/src/app/modules/deployments-adr/components/al-deployment-scan-credentials/al-deployment-scan-credentials.component.ts) after merging this.

ENG-41742: Updating Credentials Client

---

packages/assets-manager/README.md

ENG-000 - force a deploy

---

packages/convergence-utility/package.json
packages/convergence-utility/src/convergence-utility-client.ts

US - https://alertlogic.atlassian.net/browse/ENG-43558

ENG-43558 - Adding Deletable Crendential API Call

---

packages/iris/package.json
packages/iris/src/types/incident.class.ts

US: [ENG-43760](https://alertlogic.atlassian.net/browse/ENG-43760)

ENG-43760 - updating geo data property in incident class

---

packages/assets-query/package.json
packages/assets-query/src/types/index.ts

US - https://alertlogic.atlassian.net/browse/ENG-46499

ENG-46499 - Updating Target Type

---

packages/assets-query/package.json
packages/assets-query/src/types/index.ts

US - https://alertlogic.atlassian.net/browse/ENG-47249

ENG-47249 - Adding Vulnerability Type

---

packages/herald/package.json
packages/herald/src/types/heraldTypes.ts

US - https://alertlogic.atlassian.net/browse/ENG-47055

ENG-47055 - Adding Error Types to Herald

---

packages/aecontent/package.json
packages/aecontent/src/aecontent-client.ts

US: [ENG-51173](https://alertlogic.atlassian.net/browse/ENG-51173)

creating endpoints for status change of a tuning rule

---

packages/aecontent/package.json
packages/aecontent/src/aecontent-client.ts

US: [ENG-51357](https://alertlogic.atlassian.net/browse/ENG-51357)

ENG-51357: Endpoint to retrieve properties from an observation by path

---

packages/aecontent/package.json
packages/aecontent/src/aecontent-client.ts

US: [ENG-51453](https://alertlogic.atlassian.net/browse/ENG-51453)

ENG-51453: Tuning schemas update

---

packages/aecontent/package.json
packages/aecontent/src/aecontent-client.ts

US: [ENG-51768](https://alertlogic.atlassian.net/browse/ENG-51768)

ENG-51768: allow disabled rules to be queried

---

chrome_install.sh
ps_spec.yml

Previous curl to install chrome is presenting certificates issues

ENG-000: Fixing chrome certificates issue

---

packages/aecontent/package.json
packages/aecontent/src/types/aecontent-client-tuning.type.ts

US: [ENG-53302](https://alertlogic.atlassian.net/browse/ENG-53302)

ENG-53302: Tuning Multi actions changes

---

packages/assets-query/package.json
packages/assets-query/src/types/index.ts

US - https://alertlogic.atlassian.net/browse/ENG-54344

ENG-54344 - Adding Pagination Support

---

packages/assets-query/package.json
packages/assets-query/src/types/index.ts

US - https://alertlogic.atlassian.net/browse/ENG-54344

ENG-54344 - Adding Total rows field

---

packages/assets-query/package.json
packages/assets-query/src/types/index.ts

US - https://alertlogic.atlassian.net/browse/ENG-53566

ENG-53566 - Adding Last Scan Time value

---

packages/iris/package.json
packages/iris/src/types/incident.class.ts

VTT:  https://alertlogic.atlassian.net/browse/VTT-6202
Note: Add the analyticName property to iris:

VTT-6202 - Issue with Threat Intel Center IDS & LOG Analyticss

---

packages/aether/package.json
packages/aether/src/aether-client.ts

ENG-55755 - Updating Aether Client

---

packages/assets-query/package.json
packages/assets-query/src/types/index.ts

Updating Assets Query Client

---

packages/assets-query/package.json
packages/assets-query/src/index.ts

It might work, but it ain't right and I'm tired of looking at the warning in my console :)

ENG-0000 - Fix Namespace Overwrite
